-- Add mock packages with specific UUIDs for testing

-- Insert LGS Destek Paketi
INSERT INTO packages (
  id,
  name, 
  subtitle,
  description,
  price,
  original_price,
  duration,
  target_audience,
  weekly_lessons,
  lesson_details,
  features,
  is_popular,
  is_premium,
  icon,
  gradient,
  bg_color,
  text_color
) VALUES (
  'a1b2c3d4-e5f6-7890-abcd-123456789012',
  'Atlas Derslik LGS Destek Paketi',
  '8. Sınıf LGS Hazırlık',
  'LGS''de hedeflenen puanın üstüne çıkmak için motivasyon ve sınav kaygısı yönetimi ile desteklenen tam kapsamlı hazırlık programı',
  3499900,
  5500000,
  'yıllık',
  '8. sınıf öğrencileri için LGS''ye özel hazırlanmış yoğun program',
  'Haftada 10 canlı ders',
  '["Matematik: 3 Ders", "Fen Bilimleri: 3 Ders", "Türkçe: 2 Ders", "T.C. İnkılap Tarihi ve Atatürkçülük: 1 Ders", "İngilizce: 1 Ders", "Din Kültürü ve Ahlak Bilgisi Tekrar Kampı"]'::jsonb,
  '["Uzman Öğretmenler Eşliğinde İnteraktif Dersler", "10 Kişilik VIP Gruplar", "Özel Hazırlık Çalışmaları", "Psikolojik Danışman Desteği", "Düzenli Deneme Analizleri", "Ödev Takip Sistemi", "Öğrenci Paneli ve İlerleme Takip Sistemi", "Ders Kayıtları ve Gelişim Raporları", "Motivasyon ve Sınav Kaygısı Yönetimi", "Bireysel İhtiyaçlara Odaklanma", "Akademik Destek Seminerleri"]'::jsonb,
  true,
  false,
  'Crown',
  'from-orange-500 to-red-400',
  'bg-orange-50',
  'text-orange-600'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  subtitle = EXCLUDED.subtitle,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  duration = EXCLUDED.duration,
  target_audience = EXCLUDED.target_audience,
  weekly_lessons = EXCLUDED.weekly_lessons,
  lesson_details = EXCLUDED.lesson_details,
  features = EXCLUDED.features,
  is_popular = EXCLUDED.is_popular,
  is_premium = EXCLUDED.is_premium,
  icon = EXCLUDED.icon,
  gradient = EXCLUDED.gradient,
  bg_color = EXCLUDED.bg_color,
  text_color = EXCLUDED.text_color,
  updated_at = NOW();

-- Insert Okul Destek Paketi
INSERT INTO packages (
  id,
  name,
  subtitle, 
  description,
  price,
  original_price,
  duration,
  target_audience,
  weekly_lessons,
  lesson_details,
  features,
  is_popular,
  is_premium,
  icon,
  gradient,
  bg_color,
  text_color
) VALUES (
  'b2c3d4e5-f6g7-8901-bcde-234567890123',
  'Atlas Derslik Okul Destek Paketi',
  '5-6-7. Sınıflar',
  'Okula ve derslere adaptasyon süreçlerini destekleyen kapsamlı eğitim programı',
  2999900,
  4500000,
  'yıllık',
  '5., 6., 7. sınıf öğrencileri için özel tasarlanmıştır',
  'Haftada 8 canlı ders',
  '["Matematik: 2 Ders", "Fen Bilimleri: 2 Ders", "Türkçe: 2 Ders", "T.C. İnkılap Tarihi ve Atatürkçülük: 1 Ders", "İngilizce: 1 Ders"]'::jsonb,
  '["Uzman Öğretmenler Eşliğinde İnteraktif Dersler", "10 Kişilik VIP Gruplar", "Yazılılara Hazırlık Çalışmaları", "Psikolojik Danışman Desteği", "Düzenli Deneme Analizleri", "Ödev Takip Sistemi", "Öğrenci Paneli ve İlerleme Takip Sistemi", "Ders Kayıtlarına Erişim", "Sorumluluk Bilinci Geliştirme", "Akademik Destek Seminerleri"]'::jsonb,
  false,
  false,
  'BookOpen',
  'from-blue-500 to-cyan-400',
  'bg-blue-50',
  'text-blue-600'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  subtitle = EXCLUDED.subtitle,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  duration = EXCLUDED.duration,
  target_audience = EXCLUDED.target_audience,
  weekly_lessons = EXCLUDED.weekly_lessons,
  lesson_details = EXCLUDED.lesson_details,
  features = EXCLUDED.features,
  is_popular = EXCLUDED.is_popular,
  is_premium = EXCLUDED.is_premium,
  icon = EXCLUDED.icon,
  gradient = EXCLUDED.gradient,
  bg_color = EXCLUDED.bg_color,
  text_color = EXCLUDED.text_color,
  updated_at = NOW();
